# Generated by Django 5.1.5 on 2025-02-06 11:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city1', models.CharField(max_length=30)),
                ('city2', models.CharField(max_length=30)),
                ('seats_total', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('seats_available', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('timing', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_booked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.bus')),
            ],
        ),
    ]
