# Generated by Django 5.1.5 on 2025-02-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_myuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='email_otp',
            field=models.CharField(blank=True, default='', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email_otp',
            field=models.CharField(default=None, max_length=6, null=True),
        ),
    ]
