# Generated by Django 5.1.5 on 2025-02-08 06:16

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_day_remove_bus_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='bus_number',
            field=models.IntegerField(default=10000, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(10000)]),
        ),
        migrations.AddField(
            model_name='bus',
            name='days',
            field=models.ManyToManyField(to='home.day'),
        ),
        migrations.AddField(
            model_name='bus',
            name='name',
            field=models.CharField(default='bus_name', max_length=50),
        ),
        migrations.AddField(
            model_name='bus',
            name='time',
            field=models.TimeField(default=datetime.datetime(2025, 2, 8, 6, 16, 36, 669007, tzinfo=datetime.timezone.utc)),
        ),
    ]
