# Generated by Django 5.1.5 on 2025-02-08 06:27

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_bus_bus_number_bus_days_bus_name_bus_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='duration',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='bus',
            name='time',
            field=models.TimeField(default=datetime.time(6, 27, 0, 389616)),
        ),
    ]
