# Generated by Django 5.1.5 on 2025-02-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_ticket_email_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
