# Generated by Django 5.1.5 on 2025-02-08 06:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_bus_duration_alter_bus_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
