# Generated by Django 5.1.5 on 2025-02-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_bus_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='time',
        ),
        migrations.AddField(
            model_name='bus',
            name='time_end',
            field=models.CharField(default=0, max_length=4),
        ),
        migrations.AddField(
            model_name='bus',
            name='time_start',
            field=models.CharField(default=0, max_length=4),
        ),
    ]
