# Generated by Django 5.1.5 on 2025-02-08 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_bus_duration_remove_bus_time_bus_time_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='time_start',
        ),
    ]
