# Generated by Django 5.1.5 on 2025-02-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_bus_time_end_remove_bus_time_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='time_end',
            field=models.CharField(default='0000', max_length=4),
        ),
        migrations.AddField(
            model_name='bus',
            name='time_start',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
