# Generated by Django 5.1.5 on 2025-02-08 09:56

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_bus_time_end_bus_time_start'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='days',
        ),
        migrations.AlterField(
            model_name='bus',
            name='time_end',
            field=models.CharField(default='0000', max_length=4, validators=[django.core.validators.RegexValidator('^([01]\\d|2[0-3])([0-5]\\d)$', 'Enter a valiid time in 24 hour format')]),
        ),
        migrations.AlterField(
            model_name='bus',
            name='time_start',
            field=models.CharField(default='0000', max_length=4, validators=[django.core.validators.RegexValidator('^([01]\\d|2[0-3])([0-5]\\d)$', 'Enter a valiid time in 24 hour format')]),
        ),
        migrations.DeleteModel(
            name='day',
        ),
        migrations.AddField(
            model_name='bus',
            name='days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Monday', None), ('Tuesday', None), ('Wednesday', None), ('Thursday', None), ('Friday', None), ('Saturday', None), ('Sunday', None)], max_length=10), default=list, size=None),
        ),
    ]
