# Generated by Django 5.1.5 on 2025-02-08 10:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_bus_days_alter_bus_time_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='days',
        ),
        migrations.AddField(
            model_name='bus',
            name='operating_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=10), default=list, size=None),
        ),
    ]
