# Generated by Django 5.1.5 on 2025-02-08 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_bus_days_bus_operating_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='fare',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bus',
            name='time_end',
            field=models.CharField(default='0000', max_length=4, validators=[django.core.validators.RegexValidator('^([01]\\d|2[0-3])([0-5]\\d)$', 'Enter a valid time in 24 hour format')]),
        ),
        migrations.AlterField(
            model_name='bus',
            name='time_start',
            field=models.CharField(default='0000', max_length=4, validators=[django.core.validators.RegexValidator('^([01]\\d|2[0-3])([0-5]\\d)$', 'Enter a valid time in 24 hour format')]),
        ),
    ]
