# Generated by Django 5.1.5 on 2025-02-09 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_ticket_delete_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ticket',
        ),
    ]
