# Generated by Django 5.1.5 on 2025-02-09 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_ticket_pass_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass_details',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ticket'),
        ),
    ]
