# Generated by Django 5.1.5 on 2025-02-09 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_pass_details_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='pass_num',
        ),
    ]
