# Generated by Django 5.1.5 on 2025-02-09 14:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_ticket_pass_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='time_booked',
        ),
        migrations.AddField(
            model_name='ticket',
            name='date_booking',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
