# Generated by Django 5.1.5 on 2025-02-09 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_remove_ticket_time_booked_ticket_date_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='date_booking',
            new_name='dateOfBooking',
        ),
    ]
