# Generated by Django 5.1.5 on 2025-02-09 15:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_rename_date_booking_ticket_dateofbooking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='pass_details',
            new_name='passDetails',
        ),
    ]
