# Generated by Django 5.1.5 on 2025-02-12 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_rename_pass_details_passdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='users',
        ),
        migrations.DeleteModel(
            name='passDetails',
        ),
        migrations.DeleteModel(
            name='ticket',
        ),
    ]
