# Generated by Django 5.1.5 on 2025-02-13 06:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_ticket_passdetails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='account',
            new_name='wallet',
        ),
    ]
