# Generated by Django 5.1.5 on 2025-02-14 12:21

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_wallet_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), default=list, size=None)),
                ('bus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.bus')),
            ],
        ),
    ]
